source 'https://github.com/CocoaPods/Specs.git'
platform :ios,			'8.0'
inhibit_all_warnings!

target:'LCAudioPlayerDemo'

pod 'Masonry', '1.1.0'
pod 'MLCKit', :git => 'https://github.com/mlcldh/MLCKit.git'#, :commit => 'ac5c694'
pod 'LCAudioPlayer', :path => '../'
