source 'https://github.com/CocoaPods/Specs.git'
platform :ios,			'8.0'
inhibit_all_warnings!

target:'LCAudioPlayerDemo'

pod 'Masonry', '1.1.0'
pod 'MLCKit/Category', :git => 'https://github.com/mlcldh/MLCKit.git', :commit => '2eb6587'
pod 'MLCKit/Macro', :git => 'https://github.com/mlcldh/MLCKit.git', :commit => '2eb6587'
pod 'LCAudioPlayer', :path => '../'
